id="infinityfix" # required `[a-z0-9-_]{4,15}`
version="0.2.0" # required Semver Enforced!
title="Infinity Fix" # optional DEFAULT: modid
description="""
"""  # optional DEFAULT: ""
entrypoint="org.sandboxpowered.infinityfix.InfinityFix" # required
authors = [ # required 1
    "Coded",
]
url = "" # optional DEFAULT: ""
side = "COMMON" # optional [SERVER, CLIENT, COMMON] DEFAULT: "COMMON"